### ISSUE TITLE
tough-cookie jar with request failing

### ISSUE THREAD

**Issue by neilwashere** [salesforce/tough-cookie#103]
Hello - I'm struggling with tough-cookie + request and hope you can tell me what I'm doing wrong.

I'm trying to setup an initial store of cookies harvested elsewhere in order to use with a subsequent request. The docs for `request` appear to be incorrect wrt cookie store usage (at least type definitions suggest so) so I have this, using a tough-cookiejar directly rather than a request.jar():

```ts
    import requestPromise = require("request-promise");
    import tough = require("tough-cookie");
    const Cookie = tough.Cookie;


    // initial set of valid cookie strings from elsewhere
    const cookieStrings: string[] = gatherCookies();

    const cookieJar = new tough.CookieJar();
    for (const cookieString of cookiesStrings) {
        const parsedCookie = Cookie.parse(cookieString);
        cookieJar.setCookieSync(parsedCookie, `https://${parsedCookie.domain}`, {});
    }

   const requestOpts = {
       // uri, method etc elided
       jar: cookieJar
   }
   try {
   const response = await requestPromise(requestOpts)
  } catch (err) {
     // blows up with:
     // "Cannot read property 'secure' of undefined", TypeError: Cannot read property 'secure' of undefined\n    
    // at CookieJar.getCookies (/.../node_modules/tough-cookie/lib/cookie.js:1030:23)\n    
    // at CookieJar.getCookieString (/.../node_modules/tough-cookie/lib/cookie.js:1131:19)\n    
    // at Request.jar (/.../node_modules/request/request.js:1456:33)\n    
    // at Request.init (/.../node_modules/request/request.js:298:8)\n
  }
```

Squashing this is easy enough with a null check on the options at the relevant line but then other errors happen. Likely I am using this lib wrong. Should I raise this with the `request` team instead?

using:
"@types/tough-cookie": "^2.3.1",
"@types/request": "^2.0.3",
"@types/request-promise": "^4.1.38"
"request": "^2.81.0",
"request-promise": "^4.2.2",
"tough-cookie": "2.3.3",

**Comment by neilwashere** [comment]
this is a `request` issue. closing
https://github.com/request/request/issues/1939
