### ISSUE TITLE
Cannot delete property 'creationIndex' of [object Object]

### ISSUE THREAD

**Issue by Sorunome** [salesforce/tough-cookie#192]
When trying to serializeSync a cookie jar with 4.0.0 getting this:

```
TypeError: Cannot delete property 'creationIndex' of [object Object]
    at /home/sorunome/repos/skype-http/node_modules/tough-cookie/lib/cookie.js:1453:9
    at Array.map (<anonymous>)
    at /home/sorunome/repos/skype-http/node_modules/tough-cookie/lib/cookie.js:1448:36
    at MemoryCookieStore.getAllCookies (/home/sorunome/repos/skype-http/node_modules/tough-cookie/lib/memstore.js:173:5)
    at CookieJar.serialize (/home/sorunome/repos/skype-http/node_modules/tough-cookie/lib/cookie.js:1443:16)
    at CookieJar.serialize (/home/sorunome/repos/skype-http/node_modules/tough-cookie/node_modules/universalify/index.js:5:67)
    at CookieJar.serializeSync (/home/sorunome/repos/skype-http/node_modules/tough-cookie/lib/cookie.js:1642:21)
    at Object.toJson (/home/sorunome/repos/skype-http/dist/lib/interfaces/api/context.js:67:76)
    at Api.getState (/home/sorunome/repos/skype-http/dist/lib/api.js:109:34)
    at Client.get getState [as getState] (/home/sorunome/repos/mx-puppet-skype/build/client.js:48:25)
```
This is on a line `new toughCookie.CookieJar(context.cookies).serializeSync()` where `context.cookies` is of type `toughCookie.Store`. Any help would be greatly appreciated!

**Comment by Sorunome** [comment]
The problem seems to have been not correctly de-duped versions of tough-cookie and thus the `instanceof` check not properly working.
