### ISSUE TITLE
getCookiesSync crashes with Uncaught TypeError: Cannot read property 'secure' of undefined

### ISSUE THREAD

**Issue by phihag** [salesforce/tough-cookie#194]
Just calling `getCookiesSync` crashes out of the box for me with tough-cookie 2.4.3. Am I doing something wrong?

```
> new (require('tough-cookie').CookieJar)().getCookiesSync()
Uncaught TypeError: Cannot read property 'secure' of undefined
    at CookieJar.getCookies (/home/phihag/pentf/node_modules/tough-cookie/lib/cookie.js:1261:26)
    at CookieJar.getCookies (/home/phihag/pentf/node_modules/universalify/index.js:5:67)
    at CookieJar.getCookiesSync (/home/phihag/pentf/node_modules/tough-cookie/lib/cookie.js:1642:21)
```

**Comment by phihag** [comment]
My mistake; `getCookiesSync` requires a URL as the first argument.
