### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by MarkSwanson** [salesforce/tough-cookie#27]
I upgraded to node 0.11/npm 2.0 so I could workaround an issue.
Now I'm having an issue with tough-cookie:
(it doesn't compile)

...project//node_modules/tough-cookie/lib/pubsuffix.js:68
});

SyntaxError: Unexpected end of input
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.project/node_modules/tough-cookie/lib/cookie.js:25:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Any suggestions?

**Comment by inikulin** [comment]
@MarkSwanson Is issue still exists with stable node v12.0?

**Comment by arty-name** [comment]
I still see this issue in node 0.12.5

**Comment by inikulin** [comment]
@arty-name Which version of tough-cookie you use? Can you create a reproduction example?

**Comment by arty-name** [comment]
I will try. That bug is hard to reproduce, and looks like some race condition (in npm?), because individually packages install just fine.

I don't use tough-cookie directly, I use request@2.58.0

**Comment by arty-name** [comment]
[Looks like it's chromedriver's or npm's fault](https://github.com/giggio/node-chromedriver/issues/30#issuecomment-117063448)

**Comment by stash-sfdc** [comment]
Interesting... Nice find!

**Comment by tmcgee123** [comment]
Yes, second that the request module is how I'm accessing this as well, with the latest version 2.60.0.
