### ISSUE TITLE
Tough-Cookie throws error in Github Actions

### ISSUE THREAD

**Issue by rube-de** [salesforce/tough-cookie#379]
I'm running in an error from tough-cookie in my github actions, even though tough-cookie isn't used in the GA

```
/home/runner/work/contracts/contracts/node_modules/tough-cookie/lib/validators.js:77
      throw new ParameterError(options);
            ^
Error: [object Object]
    at Object.validate (/home/runner/work/contracts/contracts/node_modules/tough-cookie/lib/validators.js:77:13)
    at CookieJar.setCookie (/home/runner/work/contracts/contracts/node_modules/tough-cookie/lib/cookie.js:1119:16)
    at /home/runner/work/contracts/contracts/node_modules/tough-cookie/node_modules/universalify/index.js:13:12
    at new Promise (<anonymous>)
    at CookieJar.setCookie (/home/runner/work/contracts/contracts/node_modules/tough-cookie/node_modules/universalify/index.js:7:14)
    at Object.<anonymous> (/home/runner/work/contracts/contracts/scripts/register-helper.js:[8](https://github.com/aktionariat/contracts/actions/runs/8251073136/job/22569272028#step:6:9):11)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:11[9](https://github.com/aktionariat/contracts/actions/runs/8251073136/job/22569272028#step:6:10)7:32)
    at Function.Module._load (node:internal/modules/cjs/loader:[10](https://github.com/aktionariat/contracts/actions/runs/8251073136/job/22569272028#step:6:11)13:[12](https://github.com/aktionariat/contracts/actions/runs/8251073136/job/22569272028#step:6:13))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
https://github.com/aktionariat/contracts/actions/runs/8251073136/job/22569272028

Anyone knows what is causing this?

I saw the code in `validitors.js` got changed, is there a plan to release a new version soon?

**Comment by colincasey** [comment]
@rube-de I don't think this is an issue with `tough-cookie`, rather it seems like maybe you have something missing in your GitHub Action setup. 

Here's why I think this:
* In the `package.json` of the `aktionariat/contracts` project you linked to it has `"tough-cookie": "^4.1.2",` as a `devDependency` ([here](https://github.com/aktionariat/contracts/blob/ac9ef19c74004c5ffa35e2e0d2411929b97d0dd8/package.json#L71))
* From the stack trace given you can see this line:
    ```
    at CookieJar.setCookie (/home/runner/work/contracts/contracts/node_modules/tough-cookie/lib/cookie.js:1119:16)
    ```
* If you look up this code in the `4.1.2` branch for `tough-cookie` you'll see the [following code](https://github.com/salesforce/tough-cookie/blob/v4.1.2/lib/cookie.js#L1118-L1119):

    ```js
    setCookie(cookie, url, options, cb) {
      validators.validate(validators.isNonEmptyString(url), cb, options);
    ```
    So, based on that stack trace, the validation is failing on the argument used for `url` which is expecting a non-empty string.

* Checking `aktionariat/contracts` for `tough-cookie` usage I see the following code used [here](https://github.com/aktionariat/contracts/blob/ac9ef19c74004c5ffa35e2e0d2411929b97d0dd8/scripts/register-helper.js#L8):

    ```js
    cookieJar.setCookie('user='+cookie, process.env.AKTIONARIAT_API_URL);
    ```

This would lead me to believe that `process.env.AKTIONARIAT_API_URL` is empty.  If that's correct then you should add a check in that `register-helper.js` script that provides a more helpful message when test runs are not configured properly 😅

**Comment by rube-de** [comment]
@colincasey  thanks.
I moved getting the API in a separate function, which seemed to help, that it won't be called with an empty URL
