### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by Kepro** [salesforce/tough-cookie#99]
/var/www/node_modules/tough-cookie/lib/pubsuffix.js:109
    hashCode(): number;
              ^

SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/node_modules/tough-cookie/lib/cookie.js:34:17)

**Comment by Kepro** [comment]
after npm cache clean --force it's work again...
